###
GET http://localhost:3000/api/tasks/

###
GET http://localhost:3000/api/tasks/645dfc924421476b8f48640f

###
GET http://localhost:3000/api/tasks?size=5&page=2

###
POST http://localhost:3000/api/tasks/
Content-Type: application/json

{
    "tittle": "Hacer un sition web con React",
    "description": "Trabajo Freelance"
}

###
DELETE http://localhost:3000/api/tasks/645df980c5b97a878a1111e7

###
GET http://localhost:3000/api/tasks/done

###
PUT http://localhost:3000/api/tasks/645df97ec5b97a878a1111e5
Content-Type: application/json

{
    "done": true
}